# Generated by Django 2.0.3 on 2018-03-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(blank=True, max_length=25, null=True)),
                ('nucleotide_change', models.TextField(blank=True, null=True)),
                ('protein_change', models.CharField(blank=True, max_length=50, null=True)),
                ('other_mappings', models.TextField(blank=True, null=True)),
                ('alias', models.TextField(blank=True, null=True)),
                ('transcripts', models.TextField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=75, null=True)),
                ('reported_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('inferred_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=25, null=True)),
                ('last_evaluated', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('submitter_comment', models.TextField(blank=True, null=True)),
                ('assembly', models.CharField(blank=True, max_length=10, null=True)),
                ('chromosome', models.CharField(blank=True, max_length=2, null=True)),
                ('genomic_start', models.CharField(blank=True, max_length=15, null=True)),
                ('genomic_stop', models.CharField(blank=True, max_length=15, null=True)),
                ('ref', models.CharField(blank=True, max_length=75, null=True)),
                ('alt', models.CharField(blank=True, max_length=100, null=True)),
                ('accession', models.CharField(blank=True, max_length=25, null=True)),
                ('reported_ref', models.CharField(blank=True, max_length=75, null=True)),
                ('reported_alt', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
